### ISSUE TITLE
Issues found during anaylsis

### ISSUE THREAD

**Issue by Zukkari** [Zukkari/sonar-bulk-analyzer#2]
- Data class: 
```
[ERROR] Unable to run check class io.github.zukkari.checks.DataClassRule - DataClassRule on file 'android/src/com/google/zxing/client/android/result/supplement/SupplementalInfoRetriever.java', To help improve SonarJava, please report this problem to SonarSource : see https://www.sonarqube.org/community/
java.lang.NullPointerException: null
	at io.github.zukkari.checks.DataClassSyntax$DataClassOps.$anonfun$getters$1(DataClassRule.scala:84)
	at scala.collection.immutable.List.map(List.scala:226)
	at io.github.zukkari.checks.DataClassSyntax$DataClassOps.getters(DataClassRule.scala:84)
	at io.github.zukkari.checks.DataClassRule.visitClass(DataClassRule.scala:46)
	at org.sonar.java.model.declaration.ClassTreeImpl.accept(ClassTreeImpl.java:203)
```

**Comment by Zukkari** [comment]
- analysis-26445254-1d10-41f4-8c16-603a939185cb
